hmpps-auth:
  baseurl: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

hmpps.sqs:
  enabled: true
  provider: localstack
  queues:
    courtcasesqueue:
      queueName: court_cases_queue.fifo
      subscribeTopicId: courtcasestopic
      dlqName: court_cases_queue_dlq.fifo
      dlqMaxReceiveCount: 1
  topics:
    courtcasestopic:
      arn: "arn:aws:sns:eu-west-2:000000000000:court-cases-topic.fifo"

# Localstack settings
aws:
  region-name: eu-west-2
  localstack-endpoint-url: "http://localhost:4566"
  sqs:
    access_key_id: foobar
    secret: foobar
    queue_name: "court_cases_queue.fifo"
    dlq_name: "court_cases_queue_dlq.fifo"
  sns:
    access_key_id: foobar
    secret: foobar
    topic_arn: "arn:aws:sns:eu-west-2:000000000000:court-cases-topic.fifo"
    topic_name: court-cases-topic
  s3:
    access_key_id: foobar
    secret_access_key: foobar
    bucket_name: cpg-s3-bucket
