name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "11 5 * * MON-FRI" # Every weekday at 05:11 UTC
jobs:
  security-veracode-pipeline-scan:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@be0bda171344a1d3bd92fc8ce945a0204cbac33b # v2.14.10
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
